FONT = ('Courier', 16, 'normal')
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
TITLE = 'Breakout!'
BALL_SIZE = 0.5
PADDLE_WIDTH = 5
PADDLE_SPEED = 50
LIVES = 3
BRICKS_COUNT = 14
BRICK_GAP = 10
UPPER_GAP = 120
CONV = 20

BRICK_WIDTH = (SCREEN_WIDTH - BRICK_GAP * 2) / BRICKS_COUNT - BRICK_GAP

BG_COLOR = '#191919'
FONT_COLOR = '#A9A9A9'
PADDLE_COLOR = '#03a1fc'
BALL_COLOR = '#FFFFFF'
